### ISSUE TITLE
What is this patch: wrote better loop condition ?

### ISSUE THREAD

**Issue by LudovicRousseau** [simonibus/libfreefare-pcsc#1]
In commit https://github.com/simonibus/libfreefare-pcsc/commit/f4fd64f926e95e84b14e83cfb8d76a2a293a68ea

You added an auto-generated file:  `examples/mifare-desfire-info-pcsc` that is just a bash wrapper.

Maybe you wanted to modify the source code  `examples/mifare-desfire-info-pcsc.c` instead?

**Comment by simonibus** [comment]
You're right, the file was not in .gitignore and thus accidently submitted ;)
My Intention was to modify the source code of examples/mifare-desfire-info-pcsc.c
